import './config.js';
const URL=window.KING_DRIVER_SUPABASE_URL, KEY=window.KING_DRIVER_SUPABASE_PUBLISHABLE_KEY;
const SITE_URL='https://king-driver.pages.dev';
const REDIRECT_URL=`${SITE_URL}/auth.html`;
const $=id=>document.getElementById(id), msg=$('message');
function setMessage(t){msg.textContent=t;}
async function request(path,options={}){const token=options.accessToken||KEY;const r=await fetch(URL+path,{...options,headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.msg||d.error_description||d.message||'Falha na operação.');return d;}
async function finish(data, selectedRole){sessionStorage.setItem('king_driver_access_token',data.access_token);if(data.refresh_token)sessionStorage.setItem('king_driver_refresh_token',data.refresh_token);sessionStorage.setItem('king_driver_role',selectedRole);setMessage('Login realizado. Abrindo o King Driver...');setTimeout(()=>location.href=selectedRole==='admin'?'admin.html':'index.html',300);}
async function consumeRedirectSession(){const hash=new URLSearchParams(location.hash.replace(/^#/,'?'));const accessToken=hash.get('access_token');const type=hash.get('type');if(!accessToken)return;if(type==='recovery'){setMessage('Link de recuperação confirmado.');return;}setMessage('E-mail confirmado. Entrando no King Driver...');try{const p=await request('/rest/v1/profiles?select=role&limit=1',{accessToken});const role=p[0]?.role||'passenger';await finish({access_token:accessToken,refresh_token:hash.get('refresh_token')||''},role);}catch(e){setMessage(e.message||'E-mail confirmado. Faça login para continuar.');}}
$('signup').onclick=async()=>{try{const email=$('email').value.trim(),password=$('password').value,selectedRole=$('role').value,fullName=$('full_name').value.trim(),phone=$('phone').value.trim();if(!fullName)throw Error('Informe seu nome completo.');if(!email||password.length<6)throw Error('Informe e-mail e senha com pelo menos 6 caracteres.');setMessage(`Criando conta para ${email}...`);const d=await request('/auth/v1/signup?redirect_to='+encodeURIComponent(REDIRECT_URL),{method:'POST',body:JSON.stringify({email,password,data:{role:selectedRole,full_name:fullName,phone}})});if(d.access_token){await finish(d,selectedRole);return;}setMessage(`Conta criada. Solicitação de confirmação enviada para ${email}. Verifique Entrada e Spam.`);$('resend').hidden=false;$('resend').dataset.email=email;}catch(e){setMessage(e.message);}};
$('resend').onclick=async()=>{const email=$('resend').dataset.email||$('email').value.trim();if(!email){setMessage('Informe seu e-mail.');return;}try{setMessage(`Enviando novamente para ${email}...`);await request('/auth/v1/resend',{method:'POST',body:JSON.stringify({type:'signup',email})});setMessage(`Novo e-mail de confirmação solicitado para ${email}. Verifique Entrada e Spam.`);}catch(e){setMessage(e.message);}};
$('login').onclick=async()=>{try{const email=$('email').value.trim(),password=$('password').value;if(!email||!password)throw Error('Informe e-mail e senha.');setMessage('Entrando...');const d=await request('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});const p=await request(`/rest/v1/profiles?select=role,full_name&id=eq.${encodeURIComponent(d.user?.id||'')}`,{accessToken:d.access_token});await finish(d,p[0]?.role||$('role').value);}catch(e){setMessage(e.message);}};
consumeRedirectSession();
