import './config.js';
const URL=window.KING_DRIVER_SUPABASE_URL,KEY=window.KING_DRIVER_SUPABASE_PUBLISHABLE_KEY,TK='king_driver_access_token',RK='king_driver_role';
const $=id=>document.getElementById(id),msg=$('message');const say=t=>{if(msg)msg.textContent=t};
function base(){const p=location.pathname||'/';return p.endsWith('/')?p:p.slice(0,p.lastIndexOf('/')+1)}
const REDIRECT=`${location.origin}${base()}auth.html`;
async function api(path,opt={}){const token=opt.accessToken||KEY;const r=await fetch(URL+path,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.msg||d.error_description||d.message||d.error||'Falha na operação.');e.status=r.status;throw e}return d}
function uid(t){try{const p=t.split('.')[1]?.replace(/-/g,'+').replace(/_/g,'/');return p?JSON.parse(atob(p)).sub:''}catch(_){return ''}}
async function enter(data,role){if(!data?.access_token)throw Error('A sessão de acesso não foi recebida.');sessionStorage.setItem(TK,data.access_token);if(data.refresh_token)sessionStorage.setItem('king_driver_refresh_token',data.refresh_token);const id=uid(data.access_token);if(id){try{const p=(await api(`/rest/v1/profiles?select=id,full_name,phone,role&id=eq.${encodeURIComponent(id)}&limit=1`,{accessToken:data.access_token}))[0];if(p)role=p.role||role}catch(_){} }sessionStorage.setItem(RK,role||'passenger');say('Acesso confirmado. Abrindo o King Driver...');setTimeout(()=>location.href='app.html',250)}
function explain(e,f){const t=String(e?.message||'').toLowerCase();if(e?.status===429||t.includes('rate limit')||t.includes('too many'))return'Limite temporário de envio. Aguarde alguns minutos.';if(t.includes('email not confirmed'))return'E-mail ainda não confirmado. Use Reenviar confirmação.';if(t.includes('redirect'))return'O retorno do e-mail ainda não está autorizado no Supabase. Autorize a URL do King Driver nas URLs de autenticação.';return e?.message||f}
async function send(){const email=$('email')?.value.trim().toLowerCase()||'',name=$('full_name')?.value.trim()||'',phone=$('phone')?.value.trim()||'',role=$('role')?.value||'passenger';if(!email)throw Error('Informe seu e-mail.');await api(`/auth/v1/otp?redirect_to=${encodeURIComponent(REDIRECT)}`,{method:'POST',body:JSON.stringify({email,create_user:true,data:{role,full_name:name,phone}})});sessionStorage.setItem(RK,role);if($('resend')){$('resend').hidden=false;$('resend').dataset.email=email}say(`E-mail de acesso solicitado para ${email}. Verifique também Spam/Promoções.`)}
$('signup')?.addEventListener('click',async()=>{try{const email=$('email').value.trim().toLowerCase(),password=$('password').value||'',role=$('role').value||'passenger',name=$('full_name').value.trim(),phone=$('phone').value.trim();if(!name)throw Error('Informe seu nome completo.');if(!email||password.length<6)throw Error('Informe e-mail e senha com pelo menos 6 caracteres.');say('Criando conta...');const d=await api(`/auth/v1/signup?redirect_to=${encodeURIComponent(REDIRECT)}`,{method:'POST',body:JSON.stringify({email,password,data:{role,full_name:name,phone}})});if(d.access_token)return enter(d,role);sessionStorage.setItem(RK,role);if($('resend')){$('resend').hidden=false;$('resend').dataset.email=email}say(`Conta criada para ${email}. Confirme o e-mail para liberar o acesso.`)}catch(e){say(explain(e,'Não foi possível criar a conta.'))}});
$('login')?.addEventListener('click',async()=>{try{const email=$('email').value.trim().toLowerCase(),password=$('password').value||'';if(!email||!password)throw Error('Informe e-mail e senha.');say('Entrando...');const d=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});await enter(d,'passenger')}catch(e){say(explain(e,'Não foi possível entrar.'))}});
$('magic_link')?.addEventListener('click',async()=>{try{say('Enviando e-mail de acesso...');await send()}catch(e){say(explain(e,'Não foi possível enviar o e-mail.'))}});
$('resend')?.addEventListener('click',async()=>{try{if($('resend').dataset.email)$('email').value=$('resend').dataset.email;await send()}catch(e){say(explain(e,'Não foi possível reenviar o e-mail.'))}});
(async()=>{const h=new URLSearchParams(location.hash.replace(/^#/,'?')),t=h.get('access_token');if(h.get('error_description')){say(decodeURIComponent(h.get('error_description').replace(/\+/g,' ')));return}if(!t)return;history.replaceState(null,'',location.pathname+location.search);try{await enter({access_token:t,refresh_token:h.get('refresh_token')||''},sessionStorage.getItem(RK)||'passenger')}catch(e){say(explain(e,'E-mail confirmado. Faça login para continuar.'))}})();
