const state={screen:'home',role:null,user:null,rides:JSON.parse(localStorage.getItem('kd-rides')||'[]')};
const $=id=>document.getElementById(id);
const save=()=>localStorage.setItem('kd-rides',JSON.stringify(state.rides));
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function layout(content){$('app').innerHTML=`<div class="shell">${content}</div>`}
function home(){layout(`<div class="brand"><div class="crown">♛</div><h1>King Drive <span class="gold">Sabará</span></h1><div class="muted">Mobilidade urbana</div></div><div class="card"><h2>Como você quer usar?</h2><div class="grid"><button class="btn primary" onclick="choose('passenger')">Passageiro</button><button class="btn dark" onclick="choose('driver')">Motorista</button></div></div><div class="notice">Base própria do aplicativo. Os dados desta versão ficam no aparelho para testes de fluxo.</div>`)}
function choose(role){state.role=role;state.screen='login';render()}
function login(){layout(`<div class="brand"><div class="crown">♛</div><h1>King Drive <span class="gold">Sabará</span></h1></div><div class="card"><h2>${state.role==='driver'?'Acesso do motorista':'Acesso do passageiro'}</h2><div class="field"><label>Nome</label><input id="name" placeholder="Seu nome"></div><div class="field"><label>Telefone</label><input id="phone" placeholder="(31) 99999-9999"></div><button class="btn primary" onclick="enter()">Entrar</button><button class="btn dark" onclick="home()">Voltar</button></div>`)}
function enter(){const name=$('name').value.trim();if(!name)return alert('Informe seu nome.');state.user={name,phone:$('phone').value};state.screen=state.role==='driver'?'driver':'passenger';render()}
function passenger(){layout(`<div class="top"><div><b>Olá, ${state.user.name}</b><div class="muted">Onde você quer ir?</div></div><span class="pill">Passageiro</span></div><div class="card"><div class="field"><label>Origem</label><input id="from" placeholder="Ex.: Centro, Sabará"></div><div class="field"><label>Destino</label><input id="to" placeholder="Ex.: Bairro Nações Unidas"></div><div class="field"><label>Valor da corrida</label><input id="fare" type="number" min="5" step="0.50" value="20"></div><button class="btn primary" onclick="requestRide()">Solicitar corrida</button></div>${state.rides.filter(r=>r.passenger===state.user.name).map(rideCard).join('')}<nav class="nav"><button class="active">Início</button><button onclick="profile()">Conta</button><button onclick="logout()">Sair</button></nav>`)}
function requestRide(){const from=$('from').value.trim(),to=$('to').value.trim(),fare=Number($('fare').value);if(!from||!to||fare<5)return alert('Preencha origem, destino e valor.');state.rides.unshift({id:Date.now(),passenger:state.user.name,from,to,fare,status:'procurando motorista',driver:null});save();render();}
function rideCard(r){return `<div class="card ride"><div class="top"><b>${r.from} → ${r.to}</b><span class="price">${money(r.fare)}</span></div><p class="muted">Status: ${r.status}</p>${r.driver?`<p>Motorista: <b>${r.driver}</b></p>`:''}</div>`}
function driver(){const open=state.rides.filter(r=>r.status==='procurando motorista');layout(`<div class="top"><div><b>Olá, ${state.user.name}</b><div class="muted">Central do motorista</div></div><span class="pill">Motorista</span></div><div class="card"><h3>Corridas disponíveis</h3>${open.length?open.map(driverRide).join(''):'<p class="muted">Nenhuma corrida disponível no momento.</p>'}</div><div class="card"><h3>Resumo</h3><p>Corridas concluídas: ${state.rides.filter(r=>r.driver===state.user.name&&r.status==='concluída').length}</p><p>Repasse ao motorista: 90%</p><p>Participação da plataforma: 10%</p></div><nav class="nav"><button class="active">Corridas</button><button onclick="profile()">Conta</button><button onclick="logout()">Sair</button></nav>`)}
function driverRide(r){return `<div class="card"><b>${r.from} → ${r.to}</b><div class="top"><span class="muted">Passageiro: ${r.passenger}</span><span class="price">${money(r.fare)}</span></div><button class="btn primary" onclick="acceptRide(${r.id})">Aceitar corrida</button></div>`}
function acceptRide(id){const r=state.rides.find(x=>x.id===id);if(!r)return;r.driver=state.user.name;r.status='aceita';save();render()}
function profile(){layout(`<div class="card center"><div class="crown">♛</div><h2>${state.user.name}</h2><p class="muted">${state.role==='driver'?'Motorista':'Passageiro'}</p><button class="btn dark" onclick="render()">Voltar</button><button class="btn primary" onclick="logout()">Sair</button></div>`)}
function logout(){state.role=null;state.user=null;state.screen='home';render()}
function render(){if(state.screen==='home')home();else if(state.screen==='login')login();else if(state.screen==='passenger')passenger();else driver()}
render();
